//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenters.WCFCalc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFCalc.IDotNetCalculatorWCF")]
    public interface IDotNetCalculatorWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDotNetCalculatorWCF/Add", ReplyAction="http://tempuri.org/IDotNetCalculatorWCF/AddResponse")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDotNetCalculatorWCF/Subtract", ReplyAction="http://tempuri.org/IDotNetCalculatorWCF/SubtractResponse")]
        int Subtract(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDotNetCalculatorWCFChannel : TrainingCenters.WCFCalc.IDotNetCalculatorWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DotNetCalculatorWCFClient : System.ServiceModel.ClientBase<TrainingCenters.WCFCalc.IDotNetCalculatorWCF>, TrainingCenters.WCFCalc.IDotNetCalculatorWCF {
        
        public DotNetCalculatorWCFClient() {
        }
        
        public DotNetCalculatorWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DotNetCalculatorWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DotNetCalculatorWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DotNetCalculatorWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public int Subtract(int a, int b) {
            return base.Channel.Subtract(a, b);
        }
    }
}
