//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenters.CourseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TCCr", Namespace="http://schemas.datacontract.org/2004/07/TCLibrary")]
    [System.SerializableAttribute()]
    public partial class TCCr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourseService.ITCCourse")]
    public interface ITCCourse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCCourse/DoWork", ReplyAction="http://tempuri.org/ITCCourse/DoWorkResponse")]
        int DoWork(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCCourse/AddCourse", ReplyAction="http://tempuri.org/ITCCourse/AddCourseResponse")]
        void AddCourse(TrainingCenters.CourseService.TCCr obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITCCourseChannel : TrainingCenters.CourseService.ITCCourse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCCourseClient : System.ServiceModel.ClientBase<TrainingCenters.CourseService.ITCCourse>, TrainingCenters.CourseService.ITCCourse {
        
        public TCCourseClient() {
        }
        
        public TCCourseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCCourseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCCourseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCCourseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DoWork(int i) {
            return base.Channel.DoWork(i);
        }
        
        public void AddCourse(TrainingCenters.CourseService.TCCr obj) {
            base.Channel.AddCourse(obj);
        }
    }
}
